context:
  version: "0.9.6"
  python_min: "3.12"

package:
  name: mvlogics
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/m/mvlogics/mvlogics-${{ version }}.tar.gz
  sha256: e90ba4c1b2715c64bad2446334e8ba27f270dd798f6306b38bb6dbf9516d2be5

build:
  script:
    - uv pip install --python ${{ PYTHON }} --no-deps -vv .
  number: 0
  noarch: python

requirements:
  host:
    - python ${{ python_min }}.*
    - uv
  run:
    - python >=${{ python_min }}

tests:
  - python:
      python_version:
        - ${{ python_min }}.*
        - "*"
      imports:
        - mvlogics
      pip_check: true

about:
  homepage: https://github.com/jonathandung/mvlogics
  summary: 'Structured and well-equipped collection of unconventional systems logics with more than two truth values.'
  license: MIT
  license_file: LICENSE
  repository: https://github.com/jonathandung/mvlogics

extra:
  recipe-maintainers:
    - jonathandung
