context:
  version: "0.9.3"
  python_min: "3.12"

package:
  name: mvlogics
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/m/mvlogics/mvlogics-${{ version }}.tar.gz
  sha256: bcfdf2c0e27b61d691d30f26a0d54fe5d5d7a5d247b71f401e0e5637c01dba0b

build:
  script: python -m pip install . --no-deps --ignore-installed -vv
  number: 0
  noarch: python

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}

tests:
  - python:
      python_version:
        - ${{ python_min }}.*
        - "*"
      imports:
        - mvlogics
      pip_check: true

about:
  homepage: https://github.com/jonathandung/mvlogics
  summary: 'Structured and well-equipped collection of unconventional systems logics with more than two truth values.'
  license: MIT
  license_file: LICENSE
  repository: https://github.com/jonathandung/mvlogics

extra:
  recipe-maintainers:
    - jonathandung
